server:
 port: 8088

spring:
 datasource:
  username: root
  password: k200
  url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  driver-class-name: com.mysql.jdbc.Driver

mybatis:
 mapper-locatins: classpath:mapper/*.xml
 type-aliases-package: com.deng.myspringbootdemo01.model